<a href="https://colab.research.google.com/github/bansiiiv/BansiVora_MachineLearning_92400588083/blob/main/ColumnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
x=df.iloc[:,0:5]
y=df.drop(x,axis='columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age  gender  fever   cough       city
65   69  Female  102.0    Mild  Bangalore
46   19  Female  101.0    Mild     Mumbai
72   83  Female  101.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
36   38  Female  101.0    Mild  Bangalore


   has_covid
65        No
46        No
72        No
8         No
36        No

In [20]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

si= SimpleImputer()
le=LabelEncoder()

y_train.has_covid=le.fit_transform(y_train.has_covid)
y_test.has_covid=le.transform(y_test.has_covid)

x_train['fever']=si.fit_transform(x_train[['fever']])
x_test['fever']=si.transform(x_test[['fever']])

In [23]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()

x_train[['cough']]=oe.fit_transform(x_train[['cough']])
x_test[['cough']]=oe.transform(x_test[['cough']])

print()

In [25]:


from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse_output=False)

x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [19]:
from sklearn.compose import ColumnTransformer

In [28]:
transformer=[('trans1',SimpleImputer(),['fever']),
             ('tnrans2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
             ('tnans3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])]

In [30]:
ct=ColumnTransformer(transformers=transformer,remainder='passthrough').set_output(transform='pandas')

x_train_trans=ct.fit_transform(x_train)
x_train_trans.sample(5)

ValueError: could not convert string to float: 'Mild'